### ISSUE TITLE
@tanstack/solid-form: Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by nashaofu** [TanStack/form#652] opened 2024-03-25 09:39 UTC
### Describe the bug

When I execute `form.reset()` and input again, an error message will appear

### Your minimal, reproducible example

https://codesandbox.io/p/devbox/wonderful-golick-l4mp3l?file=%2Fsrc%2Findex.tsx

### Steps to reproduce

1. Open brower devtool,
2. Click "Reset"
3. Enter content in the input box

### Expected behavior

 without error.

### How often does this bug happen?

Every time

### Screenshots or Videos

https://github.com/TanStack/form/assets/19303058/1d1b7661-3d3f-4cbe-8c52-eb1d2b90d2ab

### Platform

OS: Windows
Browser: Chrome

### TanStack Form adapter

solid-form

### TanStack Form version

0.18.0

### TypeScript version

5.4.2

**Comment by crutchcorn** [comment] 2024-03-25 12:09
Duplicate of #495

**Closed** 2024-03-25 12:09 UTC
