### ISSUE TITLE
Issue with array + react + numbers

### ISSUE THREAD

**Issue by guhur** [TanStack/form#699] opened 2024-05-10 11:16 UTC
### Describe the bug

This comes from the array example. 
Some values disappear as shown in this video
-> each time I press "Add person", the age disappear.

![ScreenRecording2024-05-10at13 12 14-ezgif com-video-to-gif-converter](https://github.com/TanStack/form/assets/12297742/7c56525e-ca68-45c4-baf4-c9ab7ffb9331)

### Your minimal, reproducible example

https://codesandbox.io/p/devbox/ecstatic-wind-llvz6n

### Steps to reproduce

To reproduce this bug, press "Add person". 

### Expected behavior

I am expected that the age stays in place aside of the name.

### How often does this bug happen?

Every time

### Platform

macOS, Firefox 125.0.3

### TanStack Form adapter

react-form

### TanStack Form version

v0.19.4

### TypeScript version

v5.4.5

```[tasklist]
### Tasks
```

**Comment by Balastrong** [comment] 2024-05-12 11:56
Hey, the link you provided in the example seems to be the default arrays example.
Could you please update it with the link of a project reproducing the issue? :)

**Comment by guhur** [comment] 2024-05-17 04:34
Done :-) 

> Hey, the link you provided in the example seems to be the default arrays example. Could you please update it with the link of a project reproducing the issue? :)

Done! Sorry about that

**Comment by Balastrong** [comment] 2024-06-27 08:49
This is now fixed in #781, you can update `@tanstack/react-form` to 0.24 or higher :)

**Closed by Balastrong** 2024-06-27 08:49 UTC
