### ISSUE TITLE
Calling the reset function fails to reference isTouched and results in a Runtime Error

### ISSUE THREAD

**Issue by Toru-Takagi** [TanStack/form#430] opened 2023-09-02 14:37 UTC
### Describe the bug

The following error occurs when calling the reset function.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'isTouched')
    at onUpdate (FieldApi.js:284:1)
    at eval (index.production.js:11:695)
    at Set.forEach (<anonymous>)
    at #e (index.production.js:11:667)
    at t.Store.batch (index.production.js:11:748)
    at eval (FieldApi.js:37:1)
    at eval (index.production.js:11:695)
    at Set.forEach (<anonymous>)
    at #e (index.production.js:11:667)
    at t.Store.batch (index.production.js:11:748)
    at FormApi.eval [as update] (FormApi.js:38:1)
    at eval (useForm.js:44:1)
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
    at commitPassiveMountEffects (react-dom.development.js:24866:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:1)
    at flushPassiveEffects (react-dom.development.js:26984:1)
    at commitRootImpl (react-dom.development.js:26935:1)
    at commitRoot (react-dom.development.js:26682:1)
    at performSyncWorkOnRoot (react-dom.development.js:26117:1)
    at flushSyncCallbacks (react-dom.development.js:12042:1)
    at flushSync (react-dom.development.js:26201:1)
    at scheduleRefresh (react-dom.development.js:27795:1)
    at renderer.scheduleRefresh (renderer.js:584:1)
    at eval (react-refresh-runtime.development.js:265:1)
    at Set.forEach (<anonymous>)
    at Object.performReactRefresh (react-refresh-runtime.development.js:254:1)
    at applyUpdate (helpers.js:123:1)
    at statusHandler (helpers.js:140:1)
    at setStatus (webpack.js?ts=1693664866301:499:55)
    at webpack.js?ts=1693664866301:670:21
```

Simple code that occurs with the use of Next

```
import { useForm } from '@tanstack/react-form'
import { NextPage } from 'next'
import { useMemo } from 'react'

const FormTest: NextPage = () => {
  const { Provider, Field, Subscribe, getFormProps, reset } = useForm({
    defaultValues: useMemo(() => {
      return {
        label: '',
      }
    }, []),
    onSubmit: async (values) => {
      console.log(values)
      reset()
    },
  })

  return (
    <Provider>
      <form {...getFormProps()}>
        <Field name='label'>
          {(field) => {
            return <input type='text' {...field.getInputProps()} />
          }}
        </Field>
        <Subscribe>
          {({ canSubmit }) => (
            <button type='submit' disabled={!canSubmit}>
              Submit
            </button>
          )}
        </Subscribe>
      </form>
    </Provider>
  )
}

export default FormTest
```

### Your minimal, reproducible example

Described in the description

### Steps to reproduce

Calling the reset function

### Expected behavior

No error occurs and formValue becomes the initial value.

### How often does this bug happen?

Every time

### Platform

- OS: Mac
- Node: v18.17.1
- @tanstack/react-form: ^0.0.14
- next: 13.4.16
- react: 18.2.0
- typescript: ^5.1.6

### Tanstack Form adapter

None

### TanStack Form version

v0.0.14

### TypeScript version

v5.1.6

**Comment by crutchcorn** [comment] 2023-09-02 14:42
I believe this was fixed in: https://github.com/TanStack/form/pull/427

However, because of a mistake on my end it never got released 🤦

Let me try to manually release this and see if this solves this bug :)

**Comment by crutchcorn** [comment] 2023-09-02 14:48
Can you retest with `0.0.15`? :)

**Comment by Toru-Takagi** [comment] 2023-09-02 15:03
Thank you very much!
Indeed, by upgrading to 0.0.15, I no longer get an error when reading the RESET.

However, the values in the onSubmit argument, values, no longer reflect values.
We will try this separately.

The issue you raised has been resolved.
Thank you very much.

**Comment by crutchcorn** [comment] 2023-09-02 15:05
Oh! Interesting. Could you open a new GH issue so we can investigate that further?

I'll make sure we write a test for that issue so we don't end up with a regression once we fix it

**Closed by crutchcorn** 2023-09-02 15:05 UTC
Labels: bug
