### ISSUE TITLE
Cannot refer to FiledInfo of tanstack form with ReturnType

### ISSUE THREAD

**Issue by k70suK3-k06a7ash1** [TanStack/form#976] opened 2024-10-13 20:55 UTC
### Describe the bug

```typescript
const useCustomForm = () => {
  // Custom form logic
  const form = useFrom();
  // Return form object
  return { form }
}

const useSomething = () => {
  type FormProperties = ReturnType<typeof useCustomForm>['form']['fieldInfo'];

  const handleSomething = (from: FieldApi<FormProperties, 'photo', undefined, undefined, string>) => {
    // Handle something logic
  }

  // Return handleSomething function
  return { handleSomething }
}

```

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/inspiring-dew-c7y3rl

### Steps to reproduce

![Image](https://github.com/user-attachments/assets/30e2806a-5bc4-4c6e-a6fc-ace253471093)

### Expected behavior

Expect tsc --noEmit to pass

### How often does this bug happen?

None

### Platform

- OS [masOS]

### TanStack Form adapter

None

### TanStack Form version

0.33.0

### TypeScript version

5.5.3

**Comment by crutchcorn** [comment] 2024-11-25 06:35
Dupe of #891

**Closed by crutchcorn** 2024-11-25 06:35 UTC
