### ISSUE TITLE
canSubmit in form is true even if some fields are unvalid

### ISSUE THREAD

**Issue by arnars** [TanStack/form#358] opened 2019-11-19 10:23 UTC
In your own example: https://codesandbox.io/s/react-form-custom-select-multi-select-inputs-6962t

The canSubmit is `true` even before the two colors in the multiselect have been set. As long as the single select have been set, it's all good.

Is this expected?

**Comment by tannerlinsley** [comment] 2019-11-20 14:44
As of right now, this is by design. I’ll look into the why ASAP and how we could make it better.

Tanner Linsley

**Comment by AndriiUhryn** [comment] 2019-12-25 10:43
This is an issue for me as well, this needs to be fixed ASAP. Thanks.

**Comment by AndriiUhryn** [comment] 2020-01-13 14:38
Any fix for this?? My buttons are all active even if an error occurred after validation, not healthy. Please fix this.

**Comment by androsj** [comment] 2020-07-15 00:17
Hi, experiencing issues with this as well. I was expecting `isValid` to remain `false` until all fields were valid (using fields with `validatePristine` enabled). I noted it seems to return `true`  **just on the 2nd render**. All other renders receive the expected value (`false`).

**Comment by manavm1990** [comment] 2023-12-12 16:08
As from today, it's still an issue. Essentially `canSubmit` lies 🤥 . I have resolved from my side by doing like this 1️⃣ :

```tsx
<div className="mt-5 place-self-center md:col-span-2">
          <formAPI.Subscribe
            selector={(state) => state}
            children={(state) => (
              <SubmitButton isValid={validateFieldMeta(state.fieldMeta)} />
            )}
          />
```

And, here is my utility function to do the full validation before 'activating' `SubmitButton`:

```ts
import { type FieldMeta } from '@tanstack/react-form';

export function validateFieldMeta(
  fieldMeta: Record<string, FieldMeta>,
): boolean {
  return Object.values(fieldMeta).every(({ isTouched, touchedErrors }) => {
    return isTouched && touchedErrors.length === 0;
  });
}
```

And, some tests ✅  for the same:

```ts
describe('validateFieldMeta', () => {
  it('returns false if all fields are not touched', () => {
    const input = {
      name: {
        isValidating: false,
        isTouched: true,
        touchedErrors: [],
        errors: [],
        errorMap: {},
      },
      email: {
        isValidating: false,
        isTouched: true,
        touchedErrors: [],
        errors: [],
        errorMap: {},
      },
      help: {
        isValidating: false,
        isTouched: false,
        touchedErrors: [],
        errors: [],
        errorMap: {},
      },
    };

    const expected = false;

    const actual = validateFieldMeta(input);

    expect(actual).toBe(expected);
  });

  it('returns false if all fields are touched but at least one has errors', () => {
    const input = {
      name: {
        isValidating: false,
        isTouched: true,
        touchedErrors: [],
        errors: [],
        errorMap: {},
      },
      email: {
        isValidating: false,
        isTouched: true,
        touchedErrors: [],
        errors: [],
        errorMap: {},
      },
      help: {
        isValidating: false,
        isTouched: true,
        touchedErrors: ['Some error'], // Field with error
        errors: [],
        errorMap: {},
      },
    };

    const expected = false;
    const actual = validateFieldMeta(input);
    expect(actual).toBe(expected);
  });

  it('returns true if all fields are touched and have no errors', () => {
    const input = {
      name: {
        isValidating: false,
        isTouched: true,
        touchedErrors: [],
        errors: [],
        errorMap: {},
      },
      email: {
        isValidating: false,
        isTouched: true,
        touchedErrors: [],
        errors: [],
        errorMap: {},
      },
      help: {
        isValidating: false,
        isTouched: true,
        touchedErrors: [],
        errors: [],
        errorMap: {},
      },
    };

    const expected = true;
    const actual = validateFieldMeta(input);
    expect(actual).toBe(expected);
  });
});
```

Only minor issue now is that whenever we use the browser's `autocomplete` features, without actually clickng 🐭  and typing ⌨️ it doesn't register as being `isTouched`.

**Comment by t-rosa** [comment] 2024-03-27 08:34
When first rendered, the onUpdate function is called and even if the default state canSubmit is set to false, this statement is always true and sets canSubmit to true :
![image](https://github.com/TanStack/form/assets/56064543/8e799177-4ecd-449a-9524-e4b168c4c435)

**Comment by crutchcorn** [comment] 2024-03-27 18:03
@t-rosa please open a new issue. This ticket is specific for the legacy codebase, not the new codebase you're reporting an issue on

**Comment by crutchcorn** [comment] 2024-06-27 11:58
Hey all, I'm closing this issue as it appears to be related to a version of the **old** non-current `@tanstack/react-form` and friend APIs. We're looking to 1.x soon enough, and I want to more easily filter down to more recent issues.

Thanks for being early adopters of our tooling! We know that it can lead to issues like this being unresolved sometimes, but we're working hard on the new iteration of Form. 

Maybe take a look and let us know what you think?

https://tanstack.com/form

Best,

- Corbin

**Closed by crutchcorn** 2024-06-27 11:58 UTC
Labels: legacy
