### ISSUE TITLE
Doubly nested array subfield infers `never` for value type

### ISSUE THREAD

**Issue by dawsonbooth** [TanStack/form#664] opened 2024-04-03 20:35 UTC
### Describe the bug

This is similar to #625 where the same `never` inference occurred under a nested array field. This was fixed in #626, but the issue is still present under multiple array fields.

[I left a comment there describing the bug](https://github.com/TanStack/form/issues/625#issuecomment-2035440820) but figured that the scope was different enough to be more appropriately defined in a new issue.

### Your minimal, reproducible example

https://stackblitz.com/edit/tanstack-form-tutv2o?file=src%2Findex.tsx

### Steps to reproduce

1. Create form with array field
2. Add another array field under the previous
3. Add a normal field under the second array field

You should end up with a structure like the following: `form.people[${number}].parents[${number}].name`

### Expected behavior

I expected the `subField.handleChange` parameter to be `Updater<string>`, but instead I got an error where it expected `UpdaterFn<never, never>`.

The explicit error message is shown in the example code and in the following screenshot.

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://github.com/TanStack/form/assets/10625031/a368abc3-c27e-4d04-aac9-6b24b45f4b5f)

### Platform

This is a type error, so this info isn't relevant.

### TanStack Form adapter

react-form

### TanStack Form version

v0.19.0

### TypeScript version

v5.4.3

**Comment by crutchcorn** [comment] 2024-04-08 22:38
What's happening here is that, while our types are correct - they are extremely complex. Complex enough that we have to add an edgecase for only calculating a specific depth (in our case, 3 deep) so that TypeScript doesn't break.

This string is reading that 3-level depth and therefore breaking. 

Tagging in our type-level perf expert @tannerlinsley to see if we can get together to investigate a potential fix

**Comment by tannerlinsley** [comment] 2024-04-16 17:03
I’ll take a look

**Comment by tannerlinsley** [comment] 2024-04-16 17:04
@chorobin might even be a better fit here. He knows way more about perf

**Comment by chorobin** [comment] 2024-04-16 17:50
Looking briefly I can see a few things that could be more efficient. I don't think these types are tail recursive optimised, is this why TS was breaking and you had to add a depth limit? Usually there's a recursive limit up to 100 with non-optimised and 1000 optimised.

**Comment by dawsonbooth** [comment] 2024-04-16 18:37
If the depth limit can be modified (by manually adding types to extend it or otherwise), then it might make sense to choose a limit that is far beyond what could be reasonably expected for the form state, like 10 or so.

**Comment by crutchcorn** [comment] 2024-04-16 18:41
@chorobin the reason we limited depth was due to TS seemingly running into OOM problems without it. Help debugging would be immensely helpful

**Comment by chorobin** [comment] 2024-04-16 19:21
Do we have a reproducer of the OOM errors?

**Comment by crutchcorn** [comment] 2024-04-18 16:57
Confirmed to be fixed by #680! Thanks @chorobin 😄😄😄

**Closed** 2024-04-18 17:04 UTC
Labels: bug
